cabal-version:      3.0
name:               groq-hs
version:            0.1.0.0
synopsis:           Haskell library for interacting with groq cloud
license:            MIT
license-file:       LICENSE
author:             chandler-barlow
maintainer:         chandlerbrlw@gmail.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md


common warnings
    ghc-options: -Wall

common opts
    default-language: GHC2024
    default-extensions:
        AllowAmbiguousTypes,
        DataKinds,
        DeriveGeneric,
        DuplicateRecordFields,
        FlexibleContexts,
        NoMonomorphismRestriction,
        TypeApplications,
        OverloadedRecordDot,
        OverloadedStrings,
        OverloadedLabels

library
    import: warnings, opts
    hs-source-dirs:   lib
    exposed-modules:  
        Utils,
        Groq,
        Groq.Types.Models,
        Groq.Types.ChatCompletion
    build-depends:    
        base,
        aeson,
        containers,
        mtl,
        data-default,
        req,
        template-haskell,
        casing,
        text,
        microlens,
        generic-lens

executable groq-chat
  import: warnings, opts
  hs-source-dirs:      groq-chat
  main-is:             Main.hs
  ghc-options:         -Wall -O2
  build-depends:
      base,
      aeson,
      data-default,
      optparse-generic,      
      mtl,
      text,
      groq-hs
  default-language:    Haskell2010

executable groq-hs-test
    import: warnings, opts
    hs-source-dirs:   test
    main-is:          Main.hs
    -- other-modules:
    build-depends:
        base,
        tasty,
        aeson,
        tasty-hunit,
        bytestring,
        tasty-hedgehog,
        file-embed,
        groq-hs
