cabal-version:      3.0
name:               groq-hs
version:            0.1.0.0
synopsis:           Haskell library for interacting with groq cloud
license:            MIT
license-file:       LICENSE
author:             chandler-barlow
maintainer:         chandlerbrlw@gmail.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md


common warnings
    ghc-options: -Wall

library
    import:           warnings
    hs-source-dirs:   lib
    default-language: GHC2024
    -- other-extensions:

    exposed-modules:  
        Utils,
        Groq,
        Groq.Types,
        Groq.Models

    build-depends:    
        base ^>=4.20.2.0,
        aeson,
        req,
        text

test-suite groq-hs-test
    import:           warnings
    default-language: GHC2024
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:

    build-depends:
        base ^>=4.20.2.0,
        groq-hs
